# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "centos/8"
  config.vm.box_url = "https://app.vagrantup.com/centos/boxes/8"

  # Install net-tools for all machines  
  config.vm.provision "shell", inline: <<-SHELL
    # yum update -y
    yum install -y net-tools
  SHELL

  config.vm.define "oouklichS" do |control|
    control.vm.hostname = "oouklichS"
    control.vm.network "private_network", ip: "192.168.56.110"
    control.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--name", "oouklichS"]
      v.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.memory = 512
      v.cpus = 1
    end
    control.vm.provision "file", source: "~/.ssh/id_ed25519.pub", destination: "/tmp/id_ed25519.pub"
    control.vm.provision "file", source: "~/.ssh/id_ed25519", destination: "/tmp/id_ed25519"
    control.vm.provision "shell", privileged: true, path: "scripts/installS.sh"
  end
  
  config.vm.define "oouklichSW" do |control|
    control.vm.hostname = "oouklichSW"
    control.vm.network "private_network", ip: "192.168.56.111"
    control.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--name", "oouklichSW"]
      v.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.memory = 512
      v.cpus = 1
    end
    control.vm.provision "file", source: "~/.ssh/id_ed25519.pub", destination: "/tmp/id_ed25519.pub"
    control.vm.provision "file", source: "~/.ssh/id_ed25519", destination: "/tmp/id_ed25519"
    control.vm.provision "shell", privileged: true, path: "scripts/installSW.sh"
  end

end
