Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  config.vm.provision "file", source: "~/.ssh/id_ed25519.pub", destination: "/tmp/id_ed25519.pub"
  config.vm.provision "file", source: "~/.ssh/id_ed25519", destination: "/tmp/id_ed25519"
  config.vm.provision "shell", inline: <<-SHELL
    mkdir -p /root/.ssh
    mv /tmp/id_ed25519*  /root/.ssh/
    chmod 400 /root/.ssh/id_ed25519*
    chown root:root  /root/.ssh/id_ed25519*
    cat /root/.ssh/id_ed25519.pub >> /root/.ssh/authorized_keys
    chmod 400 /root/.ssh/authorized_keys
    chown root:root /root/.ssh/authorized_keys
  SHELL

  config.vm.define "evlasovS" do |server|
    server.vm.hostname = "evlasovS"
    server.vm.network "private_network", ip: "192.168.56.110"
    server.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 1
    end

  server.vm.provision "shell", inline: <<-SHELL
      sudo apt install net-tools
      sudo ip link add eth1 type dummy
      sudo ip addr add 192.168.56.110/24 dev eth1
      sudo ip link set eth1 up
      export INSTALL_K3S_VERSION=v1.21.4+k3s1
      export INSTALL_K3S_EXEC="server --write-kubeconfig-mode 644 --advertise-address=192.168.56.110 --node-ip=192.168.56.110"
      curl -sfL https://get.k3s.io | sh -
    SHELL
  end

  config.vm.define "evlasovSW" do |server_worker|
    server_worker.vm.hostname = "evlasovSW"
    server_worker.vm.network "private_network", ip: "192.168.56.111"
    server_worker.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 1
  end

  server_worker.vm.provision "shell", inline: <<-SHELL
      sudo apt install net-tools
      sudo ip link add eth1 type dummy
      sudo ip addr add 192.168.56.111/24 dev eth1
      sudo ip link set eth1 up
      scp -o StrictHostKeyChecking=no root@192.168.56.110:/var/lib/rancher/k3s/server/token /tmp/token
      export INSTALL_K3S_VERSION=v1.21.4+k3s1
      export INSTALL_K3S_EXEC="agent --server https://192.168.56.110:6443 --token-file /tmp/token --node-ip=192.168.56.111"
      curl -sfL https://get.k3s.io | sh -
    SHELL
  end
end
