# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/bionic64"

  # Install net-tools for all machines  
  config.vm.provision "shell", inline: <<-SHELL
    # yum update -y
  SHELL

  config.vm.define "tphungS" do |control|
    control.vm.hostname = "tphungS"
    control.vm.network "private_network", ip: "192.168.56.110"
    control.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--name", "tphungS"]
      v.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.memory = 1024
      v.cpus = 1
    end
    control.vm.provision "file", source: "~/.ssh/id_ed25519.pub", destination: "/tmp/id_ed25519.pub"
    control.vm.provision "file", source: "~/.ssh/id_ed25519", destination: "/tmp/id_ed25519"
    control.vm.provision "shell", privileged: true, path: "scripts/installS.sh"
  end
  
  config.vm.define "tphungSW" do |control|
    control.vm.hostname = "tphungSW"
    control.vm.network "private_network", ip: "192.168.56.111"
    control.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--name", "tphungSW"]
      v.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.memory = 1024
      v.cpus = 1
    end
    control.vm.provision "file", source: "~/.ssh/id_ed25519.pub", destination: "/tmp/id_ed25519.pub"
    control.vm.provision "file", source: "~/.ssh/id_ed25519", destination: "/tmp/id_ed25519"
    control.vm.provision "shell", privileged: true, path: "scripts/installSW.sh"
  end

end
